version: "3"

services:
  db:
    image: "mysql:8.0.32"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "db:/var/lib/mysql"
  db_test:
    image: "mysql:8.0.32"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_TEST:-app_test}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - "db_test:/var/lib/mysql"
  redis:
    image: "redis:5-alpine"
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - 5672:5672
      - 15672:15672
  mailer:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db:
  db_test:
